[project]
name = "infercnvpytutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "infercnvpy>=0.6.0",
    "jupyterlab>=4.3.6",
    "matplotlib>=3.10.1",
    "scanpy>=1.11.0",
]
